# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "icu-fit"
client_id = "116375a77fd8cd8c68962564bbe03c3f"
application_url = "https://boards-alumni-sessions-replication.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://boards-alumni-sessions-replication.trycloudflare.com/auth/callback",
  "https://boards-alumni-sessions-replication.trycloudflare.com/auth/shopify/callback",
  "https://boards-alumni-sessions-replication.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "icu-init-app.myshopify.com"
